if the VRT test fails, set an error notice and exit 1. This will be expanded into posting a comment on the PR

diff --git a/.github/workflows/testprenvironment.yaml b/.github/workflows/testprenvironment.yaml
--- a/.github/workflows/testprenvironment.yaml
+++ b/.github/workflows/testprenvironment.yaml
@@ -44,4 +44,10 @@ jobs:
         run: |
           vrt_results=${{ steps.test-environment.outputs.results }}
           echo "::notice::The results from the VRT test is ${vrt_results}"
+          if [[ "false" == "${vrt_results}" ]]; then
+            echo "::error::Visual Regression Test failed. See attached artifact."
+            exit 1
+          else
+            echo "::notice::Visual Regression Test passed. Carry on, my wayward son."
+          fi
 
